// frontend/src/App.jsx
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import Navbar from './components/Nav';
import Home from './routes/Home';
import Login from './components/auth/Login';
import Register from './components/auth/Register';
import WhiskeyList from './components/whiskey/WhiskeyList';
import WhiskeyDetail from './components/whiskey/WhiskeyDetail';
import RatingForm from './components/rating/RatingForm';
import CollectionList from './components/collection/CollectionList';
import CollectionForm from './components/collection/CollectionForm';
import UserRatings from './components/rating/UserRatings';
import NotFound from './routes/NotFound';
import ProtectedRoute from './components/ProtectedRoute';
import './index.css';

function App() {
  return(
    <Router>
      <div className="min-h-screen bg-amber-50">
        <Navbar />
        <main className="container mx-auto px-4 py-6">
          <Routes>
            {/* Public Routes */}
            <Route path="/" element={<Home />} />
            <Route path="/login" element={<Login />} />
            <Route path="/register" element={<Register />} />
            <Route path="/whiskies" element={<WhiskeyList />} />
            <Route path="/whiskey/:id" element={<WhiskeyDetail />} />

            {/* Protect routes */}
            <Route path="/collection" element={
              <ProtectedRoute>
                <CollectionList />
              </ProtectedRoute>
            } />
            <Route path="/collection/add/:id" element={
              <ProtectedRoute>
                <CollectionForm />
              </ProtectedRoute>
            } />
            <Route path="/collection/edit/:id" element={
              <ProtectedRoute>
                <CollectionForm />
              </ProtectedRoute>
            } />
            <Route path="/rate/:id" element={
              <ProtectedRoute>
                <RatingForm />
              </ProtectedRoute>
            } />
            <Route path="/ratings" element={
              <ProtectedRoute>
                <UserRatings />
              </ProtectedRoute>
            } />
            
            {/* 404 Not Found */}
            <Route path="*" element={<NotFound />} />
          </Routes>
        </main>
        <footer className="bg-amber-800 text-white py-6 mt-12">
          <div className="container mx-auto px-4 text-center">
            <p>© {new Date().getFullYear()} Whiskey Collection App</p>
          </div>
        </footer>
      </div>
    </Router>
  );
}

export default App;

// frontend/src/App.svelte
<script>
  import Router from 'svelte-spa-router';
  import { wrap } from 'svelte-spa-router/wrap';
  import { authStore } from './stores/authStore';
  
  import Nav from './components/Nav.svelte';
  import Home from './routes/Home.svelte';
  import Login from './components/auth/Login.svelte';
  import Register from './components/auth/Register.svelte';
  import WhiskeyList from './components/whiskey/WhiskeyList.svelte';
  import WhiskeyDetail from './components/whiskey/WhiskeyDetail.svelte';
  import RatingForm from './components/rating/RatingForm.svelte';
  import CollectionList from './components/collection/CollectionList.svelte';
  import CollectionForm from './components/collection/CollectionForm.svelte';
  import UserRatings from './components/rating/UserRatings.svelte';
  import NotFound from './routes/NotFound.svelte';
  
  // Auth guard for protected routes
  function authGuard(detail) {
    if (!$authStore.isAuthenticated) {
      return { redirect: '/login' };
    }
  }
  
  // Define routes
  const routes = {
    // Public routes
    '/': Home,
    '/login': Login,
    '/register': Register,
    '/whiskies': WhiskeyList,
    '/whiskey/:id': WhiskeyDetail,
    
    // Protected routes
    '/collection': wrap({
      component: CollectionList,
      conditions: [authGuard]
    }),
    '/collection/add/:id': wrap({
      component: CollectionForm,
      conditions: [authGuard]
    }),
    '/collection/edit/:id': wrap({
      component: CollectionForm,
      conditions: [authGuard]
    }),
    '/rate/:id': wrap({
      component: RatingForm,
      conditions: [authGuard]
    }),
    '/ratings': wrap({
      component: UserRatings,
      conditions: [authGuard]
    }),
    
    // 404 Not Found
    '*': NotFound
  };
</script>

<div class="min-h-screen bg-amber-50">
  <Nav />
  <main class="container mx-auto px-4 py-6">
    <Router {routes} />
  </main>
  <footer class="bg-amber-800 text-white py-6 mt-12">
    <div class="container mx-auto px-4 text-center">
      <p>© {new Date().getFullYear()} Whiskey Collection App</p>
    </div>
  </footer>
</div>

<style>
  :global(body) {
    font-family: 'Inter', sans-serif;
    margin: 0;
    padding: 0;
  }
</style>
